### ISSUE TITLE
[Bug] Workflow describe does not work with archival

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/tctl#213]
"tctl wf desc" does not work with archived executions:

```
tctl wf desc -w MyArchivedWorkflow -r myarchivedworkflowrunid
Error: Describe workflow execution failed
Error Details: rpc error: code = NotFound desc = Workflow executionsRow not found.  WorkflowId: HelloSignalWorkflow, RunId: f2a6c0f7-9551-4257-98c2-198d7213b8ed
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
github.com/temporalio/tctl/cli_curr.printError({0x2b841eb, 0x22}, {0x2fac840, 0xc00019a0e8})
	github.com/temporalio/tctl/cli_curr/util.go:392 +0x21e
github.com/temporalio/tctl/cli_curr.ErrorAndExit({0x2b841eb?, 0x2fbcb40?}, {0x2fac840?, 0xc00019a0e8?})
	github.com/temporalio/tctl/cli_curr/util.go:403 +0x28
github.com/temporalio/tctl/cli_curr.describeWorkflowHelper(0xc00032e580, {0x7ffeefbffa40, 0x13}, {0x7ffeefbffa57, 0x24})
	github.com/temporalio/tctl/cli_curr/workflowCommands.go:880 +0x239
github.com/temporalio/tctl/cli_curr.DescribeWorkflow(0xc00032e580)
	github.com/temporalio/tctl/cli_curr/workflowCommands.go:845 +0x6c
github.com/temporalio/tctl/cli_curr.newWorkflowCommands.func15(0xc00032e580?)
	github.com/temporalio/tctl/cli_curr/workflow.go:196 +0x19
github.com/urfave/cli.HandleAction({0x273c0a0?, 0x2c17df0?}, 0x8?)
	github.com/urfave/cli@v1.22.5/app.go:526 +0x50
github.com/urfave/cli.Command.Run({{0x2b448a3, 0x8}, {0x0, 0x0}, {0xc000190310, 0x1, 0x1}, {0x2b91ead, 0x26}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0003316c0, 0xc000235ce0)
	github.com/urfave/cli@v1.22.5/app.go:405 +0x91b
github.com/urfave/cli.Command.startApp({{0x2b45303, 0x8}, {0x0, 0x0}, {0xc000190650, 0x1, 0x1}, {0x2b6abf9, 0x19}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:372 +0x6e7
github.com/urfave/cli.Command.Run({{0x2b45303, 0x8}, {0x0, 0x0}, {0xc000190650, 0x1, 0x1}, {0x2b6abf9, 0x19}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc000331340, {0xc0001a6000, 0x7, 0x7})
	github.com/urfave/cli@v1.22.5/app.go:277 +0x8a7
main.main()
	./main.go:45 +0xa6
```

**Comment by tsurdilo** [comment]
related server issue: https://github.com/temporalio/temporal/issues/2919
